
SELECT ?d ?m ("has_mutation" AS ?type)
       ("quality_score" AS ?P0) SAMPLE(?q)
WHERE {
    ?det icgc:donor ?d . ?det icgc:mutation ?m .
    ?det icgc:quality_score ?q .

    ?d_ rdf:type icgc-class:Donor .

    ?m_ rdf:type icgc-class:Mutation .
}
GROUP BY ?d ?m ?type
