PREFIX : <http://example.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?p1 ?p2 ("follows" AS ?type)
WHERE {
    ?p1 :follows ?p2 .

    ?p1 a :Person .

    ?p2 a :Person .
}
GROUP BY ?p1 ?p2
