
SELECT (?m AS ?nid) ("mutation" AS ?type)
       ("label" AS ?P0) SAMPLE(?l)
       ("start_position" AS ?P1) SAMPLE(?s)
WHERE {
    ?m rdf:type icgc-class:Mutation .
    OPTIONAL { ?m rdfs:label ?l }
    OPTIONAL { ?m faldo:region ?r . ?r faldo:begin ?b . ?b faldo:position ?s }
}
GROUP BY ?m
